//! gRPC service definitions and integration.
//!
//! This module handles the interaction with the gRPC layer,
//! including defining the service and integrating with the core logic.

use tonic::{Request, Response, Status};
use futures::stream::Stream;
use tracing::{debug, error};

// Import the generated protobuf types.
// This assumes the proto file has been compiled into Rust using `tonic-build` or similar.
// The actual import path depends on your project structure and build setup.
// For example, if the proto is in `grpchook/message.proto`, it might be:
// use grpchook::message_pb2::{Message, MetaInformation, ClientProvides, ServerProvides, Payload, DataPoint};

// Placeholder for the generated gRPC message types.
// These would be imported from the `message_pb2` crate generated by `tonic`.
#[derive(Debug, Clone, prost::Message)]
pub struct Message {
    #[prost(message, tag = "1")]
    pub meta_info: Option<MetaInformation>,
    #[prost(message, repeated, tag = "2")]
    pub history: Vec<DataPoint>,
    #[prost(message, tag = "3")]
    pub payload: Option<Payload>,
}

#[derive(Debug, Clone, prost::Message)]
pub struct MetaInformation {
    #[prost(string, tag = "1")]
    pub message_id: String,
    #[prost(string, tag = "2")]
    pub message_name: String,
    #[prost(message, tag = "3")]
    pub client_info: Option<ClientProvides>,
    #[prost(message, tag = "4")]
    pub server_info: Option<ServerProvides>,
}

#[derive(Debug, Clone, prost::Message)]
pub struct ClientProvides {
    #[prost(string, tag = "1")]
    pub uuid: String,
    #[prost(string, tag = "2")]
    pub name: String,
    #[prost(string, repeated, tag = "3")]
    pub requires: Vec<String>,
    #[prost(string, repeated, tag = "4")]
    pub provides: Vec<String>,
}

#[derive(Debug, Clone, prost::Message)]
pub struct ServerProvides {
    #[prost(string, tag = "1")]
    pub server_id: String,
    #[prost(string, tag = "2")]
    pub uuid: String,
    #[prost(string, tag = "3")]
    pub name: String,
}

#[derive(Debug, Clone, prost::Message)]
pub struct Payload {
    #[prost(message, tag = "1")]
    pub struct_payload: Option<google::protobuf::Struct>,
    #[prost(bytes, tag = "2")]
    pub byte_payload: Vec<u8>,
}

#[derive(Debug, Clone, prost::Message)]
pub struct DataPoint {
    #[prost(string, tag = "1")]
    pub name: String,
    #[prost(message, tag = "2")]
    pub receive_timestamp: Option<google::protobuf::Timestamp>,
    #[prost(message, tag = "3")]
    pub send_timestamp: Option<google::protobuf::Timestamp>,
    #[prost(double, tag = "4")]
    pub perf_counter: f64,
}

/// The gRPC service definition.
///
/// This trait defines the gRPC service methods.
#[tonic::async_trait]
pub trait StreamService {
    /// Handles bidirectional streaming between client and server.
    async fn data_channel(
        &self,
        request: Request<impl Stream<Item = Result<Message, Status>>>,
    ) -> Result<Response<impl Stream<Item = Result<Message, Status>>>, Status>;
}

// Implementation of the gRPC service for `BaseServer`.
// This would typically be generated by `tonic`, but we define it here to show the integration.
// The actual implementation is in `core.rs` where `handle_client_connection` is defined.

// Example of how this might be used with a concrete `BaseServer` instance.
pub struct StreamServiceImpl {
    server: crate::server::core::BaseServer,
}

impl StreamServiceImpl {
    pub fn new(server: crate::server::core::BaseServer) -> Self {
        Self { server }
    }
}

#[tonic::async_trait]
impl StreamService for StreamServiceImpl {
    async fn data_channel(
        &self,
        request: Request<impl Stream<Item = Result<Message, Status>>>,
    ) -> Result<Response<impl Stream<Item = Result<Message, Status>>>, Status> {
        debug!("Handling DataChannel request");
        self.server.handle_client_connection(request.into_inner(), &request).await
    }
}