"""Smoke-test scaffolds generated by an installed pookiepy package.

This script must run with the Python interpreter from the isolated virtual
environment under test. Generation and runtime checks use temporary working
directories outside the repository, preventing imports from the source tree.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Iterable, TextIO


COMMAND_TIMEOUT_SECONDS = 60
SERVER_STARTUP_TIMEOUT_SECONDS = 15
PROCESS_STOP_TIMEOUT_SECONDS = 10
TRACEBACK_MARKER = "Traceback (most recent call last):"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--project-root",
        type=Path,
        required=True,
        help="Repository root that must not supply the imported pookiepy package.",
    )
    return parser.parse_args()


def clean_environment() -> dict[str, str]:
    """Return child environment without source-tree import overrides."""
    environment = os.environ.copy()
    environment.pop("PYTHONPATH", None)
    environment["PYTHONNOUSERSITE"] = "1"
    return environment


def format_process_failure(
    command: Iterable[str],
    result: subprocess.CompletedProcess[str],
) -> str:
    """Build actionable diagnostics for a failed child process."""
    return (
        f"Command failed with exit code {result.returncode}: "
        f"{' '.join(command)}\n"
        f"--- stdout ---\n{result.stdout}\n"
        f"--- stderr ---\n{result.stderr}"
    )


def run_checked(
    command: list[str],
    *,
    cwd: Path,
    environment: dict[str, str],
    timeout: int = COMMAND_TIMEOUT_SECONDS,
) -> subprocess.CompletedProcess[str]:
    """Run one command and require clean completion without a traceback."""
    result = subprocess.run(
        command,
        cwd=cwd,
        env=environment,
        capture_output=True,
        text=True,
        check=False,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(format_process_failure(command, result))
    if TRACEBACK_MARKER in result.stdout or TRACEBACK_MARKER in result.stderr:
        raise RuntimeError(format_process_failure(command, result))
    return result


def assert_installed_package(project_root: Path) -> None:
    """Require pookiepy to resolve outside the repository checkout."""
    spec = importlib.util.find_spec("pookiepy")
    if spec is None or spec.origin is None:
        raise RuntimeError("Installed pookiepy package could not be located")

    package_path = Path(spec.origin).resolve()
    repository_path = project_root.resolve()
    if package_path == repository_path or repository_path in package_path.parents:
        raise RuntimeError(
            "pookiepy resolved from repository instead of isolated environment: "
            f"{package_path}"
        )
    print(f"Installed package: {package_path}", flush=True)


def generate(
    flag: str,
    output_dir: Path,
    environment: dict[str, str],
) -> subprocess.CompletedProcess[str]:
    """Run one pookiepy generation flag in an isolated output directory."""
    print(f"\n=== {flag} ===", flush=True)
    return run_checked(
        [sys.executable, "-m", "pookiepy", flag],
        cwd=output_dir,
        environment=environment,
    )


def assert_files(output_dir: Path, expected_names: set[str]) -> None:
    """Require exact top-level files produced by one generation action."""
    actual_names = {path.name for path in output_dir.iterdir() if path.is_file()}
    if actual_names != expected_names:
        raise AssertionError(
            f"Generated files differ in {output_dir}: "
            f"expected={sorted(expected_names)}, actual={sorted(actual_names)}"
        )


def compile_python_files(paths: Iterable[Path]) -> None:
    """Compile generated Python source files without importing them."""
    for path in paths:
        source = path.read_text(encoding="utf-8")
        compile(source, str(path), "exec")


def compile_proto(output_dir: Path, environment: dict[str, str]) -> None:
    """Generate Python, gRPC, and typing bindings from generated message.proto."""
    run_checked(
        [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"-I{output_dir}",
            f"--python_out={output_dir}",
            f"--grpc_python_out={output_dir}",
            f"--pyi_out={output_dir}",
            str(output_dir / "message.proto"),
        ],
        cwd=output_dir,
        environment=environment,
    )

    generated_names = {"message_pb2.py", "message_pb2_grpc.py", "message_pb2.pyi"}
    missing_names = [name for name in generated_names if not (output_dir / name).is_file()]
    if missing_names:
        raise AssertionError(f"protoc did not generate: {sorted(missing_names)}")


def validate_proto(output_dir: Path, environment: dict[str, str]) -> None:
    """Import generated bindings and validate required RPC/message descriptors."""
    code = """
import message_pb2
import message_pb2_grpc

service = message_pb2.DESCRIPTOR.services_by_name["Stream"]
method = service.methods_by_name["DataChannel"]
assert method.client_streaming
assert method.server_streaming
assert method.input_type.full_name == method.output_type.full_name
assert {"metaInfo", "history", "payload"} <= set(method.input_type.fields_by_name)
assert "Payload" in message_pb2.DESCRIPTOR.message_types_by_name
assert hasattr(message_pb2_grpc, "StreamStub")
assert hasattr(message_pb2_grpc, "StreamServicer")
assert hasattr(message_pb2_grpc, "add_StreamServicer_to_server")
"""
    run_checked(
        [sys.executable, "-c", code],
        cwd=output_dir,
        environment=environment,
    )


def pick_unused_port() -> int:
    """Ask the OS for a currently unused loopback TCP port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def read_process_log(log_file: TextIO) -> str:
    """Read a child process log while preserving its append position."""
    log_file.flush()
    log_file.seek(0)
    output = log_file.read()
    log_file.seek(0, os.SEEK_END)
    return output


def wait_for_server(
    process: subprocess.Popen[str],
    port: int,
    log_file: TextIO,
) -> None:
    """Wait until generated server accepts TCP connections or exits."""
    deadline = time.monotonic() + SERVER_STARTUP_TIMEOUT_SECONDS
    addresses = socket.getaddrinfo(
        "localhost",
        port,
        family=socket.AF_UNSPEC,
        type=socket.SOCK_STREAM,
    )
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise RuntimeError(
                f"Generated server exited during startup with code {process.returncode}\n"
                f"--- output ---\n{read_process_log(log_file)}"
            )
        for family, socktype, proto, _, address in addresses:
            try:
                with socket.socket(family, socktype, proto) as probe:
                    probe.settimeout(0.25)
                    probe.connect(address)
                    return
            except OSError:
                continue
        time.sleep(0.1)
    raise TimeoutError(f"Generated server did not listen on port {port}")


def stop_process(process: subprocess.Popen[str]) -> None:
    """Terminate one child process, escalating to kill after timeout."""
    if process.poll() is None:
        process.terminate()
        try:
            process.wait(timeout=PROCESS_STOP_TIMEOUT_SECONDS)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=PROCESS_STOP_TIMEOUT_SECONDS)


def client_code(custom_interface: bool) -> str:
    """Return finite client smoke code for standard or custom skeleton."""
    interface_argument = (
        ", proto_interface=client_skeleton.PROTO_INTERFACE"
        if custom_interface
        else ""
    )
    return (
        "import os; import client_skeleton; "
        "from pookiepy.tools import generate_message; "
        "client = client_skeleton.MyClient(port=int(os.environ['POOKIEPY_SMOKE_PORT'])); "
        f"message = generate_message('my_request'{interface_argument}); "
        "client.send_data(message); client.wait_done(); client.disconnect()"
    )


def run_generated_pair(
    server_dir: Path,
    client_dir: Path,
    environment: dict[str, str],
    *,
    custom_interface: bool = False,
) -> None:
    """Start generated server, connect generated client, then clean up server."""
    port = pick_unused_port()
    pair_environment = environment.copy()
    pair_environment["POOKIEPY_SMOKE_PORT"] = str(port)
    server_command = [
        sys.executable,
        "-c",
        (
            "import os; from server_skeleton import MyServer; "
            "MyServer(port=int(os.environ['POOKIEPY_SMOKE_PORT'])).serve_forever()"
        ),
    ]

    print(f"Starting generated pair on port {port}", flush=True)
    with tempfile.TemporaryFile(mode="w+", encoding="utf-8") as server_log:
        with subprocess.Popen(
            server_command,
            cwd=server_dir,
            env=pair_environment,
            stdout=server_log,
            stderr=subprocess.STDOUT,
            text=True,
        ) as server:
            try:
                wait_for_server(server, port, server_log)
                run_checked(
                    [sys.executable, "-c", client_code(custom_interface)],
                    cwd=client_dir,
                    environment=pair_environment,
                )
                if server.poll() is not None:
                    raise RuntimeError(
                        "Generated server exited unexpectedly with code "
                        f"{server.returncode}\n"
                        f"--- output ---\n{read_process_log(server_log)}"
                    )
            finally:
                stop_process(server)

            server_output = read_process_log(server_log)

    if TRACEBACK_MARKER in server_output:
        raise RuntimeError(
            "Generated server emitted a traceback\n"
            f"--- output ---\n{server_output}"
        )


def make_case_dir(root: Path, name: str) -> Path:
    """Create and return one empty generation-case directory."""
    path = root / name
    path.mkdir()
    return path


def run_smoke_suite(project_root: Path) -> None:
    """Exercise every generation parameter and generated runtime path."""
    environment = clean_environment()
    assert_installed_package(project_root)

    with tempfile.TemporaryDirectory(prefix="pookiepy_skeleton_smoke_") as raw_temp:
        root = Path(raw_temp)

        server_dir = make_case_dir(root, "generate-server")
        generate("--generate-server", server_dir, environment)
        assert_files(server_dir, {"server_skeleton.py"})
        compile_python_files([server_dir / "server_skeleton.py"])

        client_dir = make_case_dir(root, "generate-client")
        generate("--generate-client", client_dir, environment)
        assert_files(client_dir, {"client_skeleton.py"})
        compile_python_files([client_dir / "client_skeleton.py"])
        run_generated_pair(server_dir, client_dir, environment)

        skeletons_dir = make_case_dir(root, "generate-skeletons")
        generate("--generate-skeletons", skeletons_dir, environment)
        assert_files(skeletons_dir, {"server_skeleton.py", "client_skeleton.py"})
        compile_python_files(
            [skeletons_dir / "server_skeleton.py", skeletons_dir / "client_skeleton.py"]
        )
        run_generated_pair(skeletons_dir, skeletons_dir, environment)

        generate_all_dir = make_case_dir(root, "generate")
        generate("--generate", generate_all_dir, environment)
        assert_files(
            generate_all_dir,
            {"server_skeleton.py", "client_skeleton.py", "HOW_TO.md"},
        )
        compile_python_files(
            [generate_all_dir / "server_skeleton.py", generate_all_dir / "client_skeleton.py"]
        )
        run_generated_pair(generate_all_dir, generate_all_dir, environment)

        how_to_dir = make_case_dir(root, "generate-how-to")
        generate("--generate-how-to", how_to_dir, environment)
        assert_files(how_to_dir, {"HOW_TO.md"})
        if not (how_to_dir / "HOW_TO.md").read_text(encoding="utf-8").strip():
            raise AssertionError("Generated HOW_TO.md is empty")

        interface_dir = make_case_dir(root, "generate-interface")
        generate("--generate-interface", interface_dir, environment)
        assert_files(interface_dir, {"message.proto"})
        compile_proto(interface_dir, environment)
        validate_proto(interface_dir, environment)

        custom_dir = make_case_dir(root, "generate-interface-with-skeletons")
        generate("--generate-interface-with-skeletons", custom_dir, environment)
        assert_files(
            custom_dir,
            {"message.proto", "server_skeleton.py", "client_skeleton.py"},
        )
        compile_python_files(
            [custom_dir / "server_skeleton.py", custom_dir / "client_skeleton.py"]
        )
        compile_proto(custom_dir, environment)
        validate_proto(custom_dir, environment)
        run_checked(
            [sys.executable, "-c", "import server_skeleton, client_skeleton"],
            cwd=custom_dir,
            environment=environment,
        )
        run_generated_pair(custom_dir, custom_dir, environment, custom_interface=True)

    print("\nAll installed skeleton smoke checks passed.", flush=True)


def main() -> None:
    """Run installed skeleton smoke suite."""
    args = parse_args()
    run_smoke_suite(args.project_root)


if __name__ == "__main__":
    main()
