# pylint: disable=invalid-name  # __main__ is a reserved Python entry-point name; the pattern check does not apply here
"""
pookiepy CLI --- project scaffolding tool.

Invoked as:
    python -m pookiepy [OPTIONS]

Generates skeleton server/client files and the HOW_TO reference document into
the current working directory, giving you a ready-to-edit starting point.

Options
-------
--generate-skeletons    Write server_skeleton.py + client_skeleton.py
--generate-server       Write server_skeleton.py only
--generate-client       Write client_skeleton.py only
--generate-how-to       Write HOW_TO.md (API reference for AI / human use)
--generate-interface    Copy the default message.proto so you can customise the Payload
--generate              Equivalent to --generate-skeletons + --generate-how-to
"""

import argparse
import shutil
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Directory that contains this __main__.py (i.e. the pookiepy package dir).
_PACKAGE_DIR = Path(__file__).parent


def _locate_how_to() -> Path:
    """
    Return the path to HOW_TO.md, searching in two locations:

    1. Inside the installed package directory (pookiepy/HOW_TO.md).
       This is the path used when pookiepy is installed via pip/pdm.
    2. Inside the assets directory one level above the package directory (assets/HOW_TO.md).
       This is the path used when running directly from the source tree
       (e.g. ``python -m pookiepy`` from the project root).

    Raises FileNotFoundError if neither location contains the file.
    """
    bundled = _PACKAGE_DIR / "assets" / "HOW_TO.md"
    if bundled.exists():
        return bundled

    source_tree = _PACKAGE_DIR.parent / "assets" / "HOW_TO.md"
    if source_tree.exists():
        return source_tree

    raise FileNotFoundError(
        "HOW_TO.md not found. "
        "Re-install the pookiepy package or run from the project root."
    )


def _locate_proto() -> Path:
    """
    Return the path to the bundled message.proto, searching in two locations:

    1. Inside the installed package directory (pookiepy/message.proto).
    2. The pookiepy/ directory one level above (source tree).

    Raises FileNotFoundError if neither location contains the file.
    """
    bundled = _PACKAGE_DIR / "message.proto"
    if bundled.exists():
        return bundled

    source_tree = _PACKAGE_DIR.parent / "interface" / "message.proto"
    if source_tree.exists():
        return source_tree

    raise FileNotFoundError(
        "message.proto not found. "
        "Re-install the pookiepy package or run from the project root."
    )


# ---------------------------------------------------------------------------
# Skeleton templates
# ---------------------------------------------------------------------------

# Each template is a complete, importable Python module.  Class names, port
# numbers, and messageName strings are left as explicit placeholders so the
# developer immediately sees what to change.

_SERVER_SKELETON = '''\
"""
Server implementation --- generated by pookiepy.

Replace:
  - MyServer      → your server class name
  - 50051         → your port number
  - "my_request"  → the messageName(s) your clients will send
  - "my_response" → the messageName(s) your server will push back
"""

from pookiepy.baseserver import BaseServer, Peer, ServerConfig
from pookiepy.tools import generate_message
import pookiepy.message_pb2 as message_pb2


class MyServer(BaseServer):
    """Minimal server skeleton. Override the hooks you need."""

    def __init__(self, port: int = 50051):
        super().__init__(port=port, name="MyServer")

    # ------------------------------------------------------------------
    # Lifecycle hooks
    # ------------------------------------------------------------------

    def on_init(self):
        """Called once after __init__ completes. Set up server-side state here."""
        pass

    def on_shutdown(self):
        """Called during shutdown. Clean up resources here."""
        pass

    # ------------------------------------------------------------------
    # Client lifecycle hooks
    # ------------------------------------------------------------------

    def on_client_connect(self, request: message_pb2.PookieMessage, context) -> bool:
        """
        Called on the *first* message from a new client, before it is registered.

        request.metaInfo.clientInfo exposes:
            .uuid        --- unique ID generated by the client
            .identifier  --- human-readable name sent by the client (maps to client's ``name``)
            .provides    --- list of messageNames the client will send
            .requires    --- list of messageNames the client wants to receive

        Return True to accept the client, False to reject (triggers PERMISSION_DENIED).
        """
        return True

    def on_client_accepted(self, peer: Peer, request: message_pb2.PookieMessage):
        """
        Called after a client has been fully registered.
        peer fields are all populated at this point.
        """
        pass

    def on_client_disconnect(self, peer: Peer):
        """Called when an accepted client's stream closes."""
        pass

    # ------------------------------------------------------------------
    # PookieMessage hook
    # ------------------------------------------------------------------

    def on_receive(self, peer: Peer, request: message_pb2.PookieMessage) -> bool:
        """
        Called for every subsequent message from an accepted client.

        Return True  → the framework fans the message out to all clients whose
                       'requires' list contains this messageName.
        Return False → suppress the fan-out; handle routing yourself (e.g.
                       unicast, transform, or cache the message).

        Example --- unicast a reply back to the sender only:

            response = generate_message("my_response", struct_payload={"result": 42})
            self._data_register.add_data_for_messageName(
                peer.client_id, "my_response", response,
                targetClientId=peer.client_id,   # <-- unicast
            )
            return False
        """
        return True


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    server = MyServer(port=50051)
    server.serve_forever()   # blocks until KeyboardInterrupt or server.shutdown()
'''


_CLIENT_SKELETON = '''\
"""
Client implementation --- generated by pookiepy.

Replace:
  - MyClient      → your client class name
  - 50051         → your port number
  - "my_request"  → messageNames this client sends  (must match server expectations)
  - "my_response" → messageNames this client wants to receive
"""

from pookiepy.baseclient import BaseClient, ClientConfig
from pookiepy.tools import generate_message, struct_to_json
from pookiepy.exceptions import GrpcEmpty, ClientExit
import pookiepy.message_pb2 as message_pb2


class MyClient(BaseClient):
    """Minimal client skeleton. Override the hooks you need."""

    def __init__(self, port: int = 50051):
        super().__init__(
            name="my-client",   # human-readable name visible on the server
            port=port,
            provides=["my_request"],   # messageNames this client is allowed to send
            requires=["my_response"],  # messageNames this client wants to receive
        )

    # ------------------------------------------------------------------
    # Lifecycle hooks
    # ------------------------------------------------------------------

    def on_init(self):
        """Called after each connection attempt (initial connect and every reconnect)."""
        pass

    def on_shutdown(self):
        """Called during disconnect(). Clean up resources here."""
        pass

    # ------------------------------------------------------------------
    # PookieMessage hook
    # ------------------------------------------------------------------

    def on_receive(self, data: message_pb2.PookieMessage) -> bool:
        """
        Called by spin() / spin_forever() for each message received from the server.

        Return value is currently unused by the framework but kept for consistency.
        """
        name = data.metaInfo.messageName
        payload = struct_to_json(data.payload.structPayload)  # → dict
        # TODO: handle the incoming message
        return True


# ---------------------------------------------------------------------------
# Entry point --- illustrates the three pookiepy usage patterns
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Pattern A: hook-based receive loop (recommended for long-running clients)
    client = MyClient(port=50051)
    client.send_data(generate_message("my_request", struct_payload={"key": "value"}))
    client.spin_forever(timeout=5.0)  # calls on_receive() per message; exits on timeout
    client.disconnect()

    # Pattern B: manual polling
    # client = MyClient(port=50051)
    # client.send_data(generate_message("my_request"))
    # try:
    #     msg = client.get_data(timeout=5.0)
    # except GrpcEmpty:
    #     pass   # no message arrived within 5 s
    # except ClientExit:
    #     pass   # client was disconnected
    # client.disconnect()

    # Pattern C: context manager (auto-disconnects on exit; reusable)
    # with MyClient(port=50051) as client:
    #     client.send_data(generate_message("my_request"))
    #     client.wait_done()                  # wait until message is handed to gRPC
    #     msg = client.get_data(timeout=5.0)
'''


# Templates for --generate-interface-with-skeletons.
# Custom modules are compiled by the user, imported normally, then injected.

_SERVER_SKELETON_CUSTOM = '''\
"""
Server implementation with custom interface --- generated by pookiepy.

This skeleton uses precompiled modules generated from the local message.proto.

Steps:
  1. Edit message.proto --- add your custom fields to the Payload message.
    2. Compile message.proto using the command printed by pookiepy.
    3. Replace MyServer, port, and messageName placeholders below, then run.
"""

import message_pb2
import message_pb2_grpc
from pookiepy.baseserver import BaseServer, Peer, ServerConfig
from pookiepy.custom_interface import ProtoInterface


PROTO_INTERFACE = ProtoInterface(message_pb2, message_pb2_grpc)


class MyServer(BaseServer):
    """Server skeleton with custom interface. Override the hooks you need."""

    def __init__(
        self,
        port: int = 50051,
        proto_interface: ProtoInterface = PROTO_INTERFACE,
    ):
        super().__init__(port=port, name="MyServer", proto_interface=proto_interface)

    def on_init(self):
        """Called once after __init__ completes. Set up server-side state here."""
        pass

    def on_shutdown(self):
        """Called during shutdown. Clean up resources here."""
        pass

    def on_client_connect(self, request: message_pb2.PookieMessage, context) -> bool:
        """
        Called on the first message from a new client, before it is registered.
        Return True to accept, False to reject (triggers PERMISSION_DENIED).
        """
        return True

    def on_client_accepted(self, peer: Peer, request: message_pb2.PookieMessage):
        """Called after a client has been fully registered."""
        pass

    def on_client_disconnect(self, peer: Peer):
        """Called when an accepted client\'s stream closes."""
        pass

    def on_receive(self, peer: Peer, request: message_pb2.PookieMessage) -> bool:
        """
        Called for every subsequent message from an accepted client.

        Access your custom payload fields directly:
            value = request.payload.myCustomField

        Return True  → fan-out to all clients whose \'requires\' contains this messageName.
        Return False → suppress fan-out; handle routing yourself.
        """
        return True


if __name__ == "__main__":
    server = MyServer(port=50051)
    server.serve_forever()
'''


_CLIENT_SKELETON_CUSTOM = '''\
"""
Client implementation with custom interface --- generated by pookiepy.

This skeleton uses precompiled modules generated from the local message.proto.

Steps:
  1. Edit message.proto --- add your custom fields to the Payload message.
    2. Compile message.proto using the command printed by pookiepy.
    3. Replace MyClient, port, and messageName placeholders below, then run.
"""

import message_pb2
import message_pb2_grpc
from pookiepy.baseclient import BaseClient, ClientConfig
from pookiepy.custom_interface import ProtoInterface
from pookiepy.exceptions import GrpcEmpty, ClientExit
from pookiepy.tools import generate_message


PROTO_INTERFACE = ProtoInterface(message_pb2, message_pb2_grpc)


class MyClient(BaseClient):
    """Client skeleton with custom interface. Override the hooks you need."""

    def __init__(
        self,
        port: int = 50051,
        proto_interface: ProtoInterface = PROTO_INTERFACE,
    ):
        super().__init__(
            name="my-client",
            port=port,
            provides=["my_request"],
            requires=["my_response"],
            proto_interface=proto_interface,
        )

    def on_init(self):
        """Called after each connection attempt (initial connect and every reconnect)."""
        pass

    def on_shutdown(self):
        """Called during disconnect(). Clean up resources here."""
        pass

    def on_receive(self, data: message_pb2.PookieMessage) -> bool:
        """
        Called by spin() / spin_forever() for each received message.

        Access your custom payload fields directly:
            value = data.payload.myCustomField
        """
        name = data.metaInfo.messageName
        # TODO: handle the incoming message
        return True


if __name__ == "__main__":
    client = MyClient(port=50051)
    client.send_data(client.generate_message("my_request"))
    client.spin_forever(timeout=5.0)
    client.disconnect()
'''


# ---------------------------------------------------------------------------
# File writing helpers
# ---------------------------------------------------------------------------

def _write_file(destination: Path, content: str, *, overwrite: bool = False) -> bool:
    """
    Write *content* to *destination*.

    Returns True on success, False if the file already existed and *overwrite*
    is False (the existing file is left untouched in that case).
    """
    if destination.exists() and not overwrite:
        print(f"  [skip]  {destination.name} already exists --- not overwritten.")
        return False

    destination.write_text(content, encoding="utf-8")
    print(f"  [ok]    {destination.name} written.")
    return True


def _copy_file(source: Path, destination: Path, *, overwrite: bool = False) -> bool:
    """
    Copy *source* to *destination*.

    Returns True on success, False if the file already existed and *overwrite*
    is False.
    """
    if destination.exists() and not overwrite:
        print(f"  [skip]  {destination.name} already exists --- not overwritten.")
        return False

    shutil.copy2(source, destination)
    print(f"  [ok]    {destination.name} written.")
    return True


# ---------------------------------------------------------------------------
# Generation actions
# ---------------------------------------------------------------------------

def generate_server(output_dir: Path) -> None:
    """Write server_skeleton.py to *output_dir*."""
    _write_file(output_dir / "server_skeleton.py", _SERVER_SKELETON)


def generate_client(output_dir: Path) -> None:
    """Write client_skeleton.py to *output_dir*."""
    _write_file(output_dir / "client_skeleton.py", _CLIENT_SKELETON)


def generate_skeleton(output_dir: Path) -> None:
    """Write both server_skeleton.py and client_skeleton.py to *output_dir*."""
    generate_server(output_dir)
    generate_client(output_dir)


def generate_how_to(output_dir: Path) -> None:
    """Copy HOW_TO.md into *output_dir*."""
    try:
        source = _locate_how_to()
    except FileNotFoundError as exc:
        print(f"  [error] {exc}", file=sys.stderr)
        sys.exit(1)

    _copy_file(source, output_dir / "HOW_TO.md")


# The instructions printed after a successful --generate-interface run.
# Kept as a module-level constant so it is easy to update in one place.
_INTERFACE_INSTRUCTIONS = """
Next steps
----------
1.  Edit  message.proto  --- change the Payload message to suit your needs.
    Do NOT rename or remove the Service, PookieMessage, MetaInformation, DataPoint,
    ClientProvides, or ServerProvides definitions; pookiepy depends on them.

2.  Compile your proto (requires grpcio-tools):

        python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. --pyi_out=. message.proto

    This produces  message_pb2.py,  message_pb2_grpc.py, and  message_pb2.pyi
    next to your  message.proto.

3.  Import the generated modules and create the interface used by each client
    and server instance:

        import message_pb2
        import message_pb2_grpc
        from pookiepy.custom_interface import ProtoInterface

        proto_interface = ProtoInterface(message_pb2, message_pb2_grpc)
        server = MyServer(port=50051, proto_interface=proto_interface)
"""


def generate_interface(output_dir: Path) -> None:
    """Copy message.proto into *output_dir* and print usage instructions."""
    try:
        source = _locate_proto()
    except FileNotFoundError as exc:
        print(f"  [error] {exc}", file=sys.stderr)
        sys.exit(1)

    _copy_file(source, output_dir / "message.proto")
    print(_INTERFACE_INSTRUCTIONS)


def generate_interface_with_skeletons(output_dir: Path) -> None:
    """Copy message.proto and write server/client skeletons that use it."""
    generate_interface(output_dir)
    _write_file(output_dir / "server_skeleton.py", _SERVER_SKELETON_CUSTOM)
    _write_file(output_dir / "client_skeleton.py", _CLIENT_SKELETON_CUSTOM)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    """Build and return the argument parser for the pookiepy CLI."""
    parser = argparse.ArgumentParser(
        prog="python -m pookiepy",
        description=(
            "pookiepy scaffolding tool.\n\n"
            "Generates skeleton server/client files and the HOW_TO reference\n"
            "document into the current working directory."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  python -m pookiepy --generate                          # skeleton + HOW_TO\n"
            "  python -m pookiepy --generate-skeletons                  # server + client only\n"
            "  python -m pookiepy --generate-server                   # server only\n"
            "  python -m pookiepy --generate-client                   # client only\n"
            "  python -m pookiepy --generate-how-to                   # HOW_TO.md only\n"
            "  python -m pookiepy --generate-interface"
            "                # message.proto + instructions\n"
            "  python -m pookiepy --generate-interface-with-skeletons"
            "  # proto + matching skeletons\n"
        ),
    )

    parser.add_argument(
        "--generate",
        action="store_true",
        help="Generate server_skeleton.py, client_skeleton.py, and HOW_TO.md",
    )
    parser.add_argument(
        "--generate-skeletons",
        action="store_true",
        help="Generate server_skeleton.py and client_skeleton.py",
    )
    parser.add_argument(
        "--generate-server",
        action="store_true",
        help="Generate server_skeleton.py only",
    )
    parser.add_argument(
        "--generate-client",
        action="store_true",
        help="Generate client_skeleton.py only",
    )
    parser.add_argument(
        "--generate-how-to",
        action="store_true",
        help="Copy HOW_TO.md into the current directory",
    )
    parser.add_argument(
        "--generate-interface",
        action="store_true",
        help="Copy message.proto into the current directory and print customisation instructions",
    )
    parser.add_argument(
        "--generate-interface-with-skeletons",
        action="store_true",
        help=(
            "Copy message.proto and write server_skeleton.py + client_skeleton.py "
            "that inject precompiled custom protobuf modules"
        ),
    )

    return parser


def main() -> None:
    """Parse CLI arguments and dispatch to the requested generation action(s)."""
    parser = _build_parser()
    args = parser.parse_args()

    # If no flag was given, show help and exit cleanly.
    if not any(vars(args).values()):
        parser.print_help()
        sys.exit(0)

    output_dir = Path.cwd()
    print(f"pookiepy --- writing files to: {output_dir}\n")

    # --generate expands to --generate-skeletons + --generate-how-to
    if args.generate:
        generate_skeleton(output_dir)
        generate_how_to(output_dir)
        return

    # Individual flags --- execute each that was requested.
    # --generate-skeletons expands to --generate-server + --generate-client.
    if args.generate_skeletons:
        generate_skeleton(output_dir)

    if args.generate_server:
        generate_server(output_dir)

    if args.generate_client:
        generate_client(output_dir)

    if args.generate_how_to:
        generate_how_to(output_dir)

    if args.generate_interface:
        generate_interface(output_dir)

    if args.generate_interface_with_skeletons:
        generate_interface_with_skeletons(output_dir)


if __name__ == "__main__":
    main()
