# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_if/message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'custom_if/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ustom_if/message.proto\x12\x10message.proto.v3\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x98\x01\n\x07Message\x12\x33\n\x08metaInfo\x18\x01 \x01(\x0b\x32!.message.proto.v3.MetaInformation\x12,\n\x07history\x18\x02 \x03(\x0b\x32\x1b.message.proto.v3.DataPoint\x12*\n\x07payload\x18\x03 \x01(\x0b\x32\x19.message.proto.v3.Payload\"\xea\x01\n\x0fMetaInformation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tmessageId\x18\x02 \x01(\t\x12\x14\n\x0cresponseToId\x18\x03 \x01(\t\x12\x34\n\nclientInfo\x18\x04 \x01(\x0b\x32 .message.proto.v3.ClientProvides\x12\x34\n\nserverInfo\x18\x05 \x01(\x0b\x32 .message.proto.v3.ServerProvides\x12\x13\n\x0bmessageName\x18\x06 \x01(\t\"\x97\x01\n\tDataPoint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x10receiveTimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rsendTimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bperfCounter\x18\x04 \x01(\x01\"P\n\x0e\x43lientProvides\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08requires\x18\x03 \x03(\t\x12\x10\n\x08provides\x18\x04 \x03(\t\">\n\x0eServerProvides\x12\x10\n\x08serverId\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"$\n\x07Payload\x12\x19\n\x11onlyAFloatPayload\x18\x01 \x01(\x02\x32Q\n\x06Stream\x12G\n\x0b\x44\x61taChannel\x12\x19.message.proto.v3.Message\x1a\x19.message.proto.v3.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_if.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=109
  _globals['_MESSAGE']._serialized_end=261
  _globals['_METAINFORMATION']._serialized_start=264
  _globals['_METAINFORMATION']._serialized_end=498
  _globals['_DATAPOINT']._serialized_start=501
  _globals['_DATAPOINT']._serialized_end=652
  _globals['_CLIENTPROVIDES']._serialized_start=654
  _globals['_CLIENTPROVIDES']._serialized_end=734
  _globals['_SERVERPROVIDES']._serialized_start=736
  _globals['_SERVERPROVIDES']._serialized_end=798
  _globals['_PAYLOAD']._serialized_start=800
  _globals['_PAYLOAD']._serialized_end=836
  _globals['_STREAM']._serialized_start=838
  _globals['_STREAM']._serialized_end=919
# @@protoc_insertion_point(module_scope)
